[package]
name = "zk_snarks"
version = "0.1.0"
edition = "2018"

[dependencies]
ark-circom = { git = "https://github.com/gakonst/ark-circom.git" }
ark-bn254 = "0.4.0" 
ark-groth16 = "0.4.0" 
ark-snark = "0.4.0" 
rand = "0.8.5"
